QStringList is no longer a class, don't forward-declare it as such
Qt6 switched QStringList to a typedef, and declaring it as a class leads
to the following error:

error: using typedef-name 'using QStringList = class QList<QString>' after 'class'

We can just drop the forward declaration. Qt5 doesn't appear to need it
either.